use super::*;

fn sample_lock() -> Lock {
    Lock {
        minecraft: "1.21.1".into(),
        loader: "neoforge".into(),
        targets: vec!["curseforge".into(), "modrinth".into()],
        mod_: vec![LockEntry {
            id: "sodium".into(),
            name: "Sodium".into(),
            version: "Sodium 0.8.12 for NeoForge 1.21.1".into(),
            modrinth: Some(LockModrinth {
                slug: "sodium".into(),
                project_id: "AANobbMI".into(),
                version_id: "S3DUMfBo".into(),
                filename: "sodium-neoforge-0.8.12+mc1.21.1.jar".into(),
                url: Some("https://cdn.modrinth.com/data/x/sodium.jar".into()),
                size: 1,
                hashes: LockHashes::new(Some("aaa".into()), Some("bbb".into()), None),
                dependencies: vec![LockDep { id: "citadel".into(), optional: false }],
            }),
            curseforge: Some(LockCurseForge {
                project_id: 394_468,
                file_id: 12_345,
                filename: "sodium.jar".into(),
                url: Some("https://edge.forgecdn.net/files/sodium.jar".into()),
                size: 2,
                hashes: LockHashes::new(Some("ccc".into()), None, Some("ddd".into())),
                dependencies: vec![],
                slug: "sodium".into(),
            }),
        }],
        resourcepack: vec![],
        datapack: vec![],
        shader: vec![],
    }
}

#[test]
fn lock_renders_in_user_shape() {
    let out = render(&sample_lock());
    assert!(out.starts_with("# This file is automatically @generated by Easypacker."));
    assert!(out.contains("version = 1"));
    assert!(out.contains("minecraft = \"1.21.1\""));
    assert!(out.contains("loader = \"neoforge\""));
    assert!(out.contains("targets = [\"curseforge\", \"modrinth\"]"));
    // no sub-tables — platforms are multi-line inline tables
    assert!(!out.contains("[mod.modrinth]"));
    assert!(out.contains("[[mod]]"));
    assert!(
        out.contains(
            "modrinth = {\n    slug = \"sodium\",\n    project_id = \"AANobbMI\",\n    version_id = \"S3DUMfBo\","
        ),
        "modrinth block wrong:\n{out}"
    );
    assert!(out.contains("hashes = {\n        sha1 = \"aaa\",\n        sha512 = \"bbb\"\n    }"));
    assert!(out.contains("curseforge = {\n    project_id = 394468,\n    file_id = 12345,"));
    assert!(out.contains("hashes = {\n        sha1 = \"ccc\",\n        md5 = \"ddd\"\n    }"));
    // valid TOML, round-trips
    let parsed: toml::Value = toml::from_str(&out).unwrap();
    assert_eq!(parsed["version"].as_integer(), Some(1));
    assert_eq!(parsed["minecraft"].as_str(), Some("1.21.1"));
    let m = &parsed["mod"][0];
    assert_eq!(m["id"].as_str(), Some("sodium"));
    assert_eq!(m["modrinth"]["version_id"].as_str(), Some("S3DUMfBo"));
    assert_eq!(m["modrinth"]["hashes"]["sha512"].as_str(), Some("bbb"));
    assert_eq!(m["curseforge"]["file_id"].as_integer(), Some(12_345));
    assert_eq!(m["curseforge"]["hashes"]["md5"].as_str(), Some("ddd"));
    // Dependency edge (cargo-style id list, multi-line like Cargo.lock).
    assert!(out.contains("dependencies = [\n    \"citadel\",\n]"), "not multiline:\n{out}");
    assert_eq!(m["dependencies"].as_array().unwrap(), &[toml::Value::String("citadel".into())]);
}

#[test]
fn render_omits_missing_url_and_hashes() {
    let mut lock = sample_lock();
    let entry = &mut lock.mod_[0];
    entry.modrinth.as_mut().unwrap().url = None;
    entry.modrinth.as_mut().unwrap().hashes = None;
    let out = render(&lock);
    let mr_block = out.split("curseforge = ").next().unwrap();
    assert!(!mr_block.contains("url"));
    assert!(!mr_block.contains("hashes"));
    toml::from_str::<toml::Value>(&out).unwrap();
}

#[test]
fn rewrite_edges_keeps_required_only_and_rewrites_to_slugs() {
    let mut entry = LockEntry {
        id: "tfc".into(),
        name: "TFC".into(),
        version: "4.2.7".into(),
        modrinth: Some(LockModrinth {
            slug: "terrafirmacraft".into(),
            project_id: "JaCEZUhg".into(),
            version_id: "eBIfZlEM".into(),
            filename: "tfc.jar".into(),
            url: None,
            size: 1,
            hashes: None,
            dependencies: vec![
                LockDep { id: "nU0bVIaL".into(), optional: false }, // patchouli, required
                LockDep { id: "someopt".into(), optional: true },    // optional -> dropped
            ],
        }),
        curseforge: None,

    };
    let slug_of = std::collections::HashMap::from([
        ((Platform::Modrinth, "nU0bVIaL".to_string()), "patchouli".to_string()),
    ]);
    let known = std::collections::HashSet::from(["patchouli".to_string()]);
    rewrite_edges(&mut entry, &slug_of, &known);
    let deps = &entry.modrinth.as_ref().unwrap().dependencies;
    // Only the required dep remains, rewritten to its slug.
    assert_eq!(deps.len(), 1);
    assert_eq!(deps[0].id, "patchouli");
    assert!(!deps[0].optional);
}

#[test]
fn rewrite_edges_drops_unknown_deps() {
    let mut entry = LockEntry {
        id: "tfc".into(),
        name: "TFC".into(),
        version: "4.2.7".into(),
        modrinth: Some(LockModrinth {
            slug: "terrafirmacraft".into(),
            project_id: "JaCEZUhg".into(),
            version_id: "eBIfZlEM".into(),
            filename: "tfc.jar".into(),
            url: None,
            size: 1,
            hashes: None,
            dependencies: vec![LockDep { id: "unknown".into(), optional: false }],
        }),
        curseforge: None,

    };
    rewrite_edges(&mut entry, &std::collections::HashMap::new(), &std::collections::HashSet::new());
    assert!(entry.modrinth.as_ref().unwrap().dependencies.is_empty());
}
