//! Easypacker.lock generation — resolves Easypacker.toml against
//! Modrinth/CurseForge and pins exact files, download urls and hashes.
//! Regenerated on every run; never edit by hand (cargo-style).

use crate::api::{CurseForgeClient, ModrinthClient};
use crate::api::types::{DepKind, Platform};
use crate::config::Config;
use crate::project::{CATEGORIES, Manifest, ModSpec, tstr};
use color_eyre::eyre::{Result, bail};
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use std::path::Path;
use std::sync::Arc;

pub const LOCK_FILE: &str = "Easypacker.lock";
const LOCK_HEADER: &str = "# This file is automatically @generated by Easypacker.\n# It is not intended for manual editing.\n";

struct Lock {
    minecraft: String,
    loader: String,
    targets: Vec<String>,
    mod_: Vec<LockEntry>,
    resourcepack: Vec<LockEntry>,
    datapack: Vec<LockEntry>,
    shader: Vec<LockEntry>,
}

struct LockEntry {
    id: String,
    name: String,
    version: String,
    modrinth: Option<LockModrinth>,
    curseforge: Option<LockCurseForge>,
}

struct LockModrinth {
    slug: String,
    project_id: String,
    version_id: String,
    filename: String,
    url: Option<String>,
    size: u64,
    hashes: Option<LockHashes>,
    /// ids this version depends on.
    dependencies: Vec<LockDep>,
}

struct LockCurseForge {
    project_id: i64,
    file_id: i64,
    filename: String,
    url: Option<String>,
    size: u64,
    hashes: Option<LockHashes>,
    /// ids this file depends on.
    dependencies: Vec<LockDep>,
}

struct LockHashes {
    sha1: Option<String>,
    sha512: Option<String>,
    md5: Option<String>,
}

#[derive(Clone)]
struct LockDep {
    id: String,
    optional: bool,
}

impl LockHashes {
    fn new(sha1: Option<String>, sha512: Option<String>, md5: Option<String>) -> Option<Self> {
        if sha1.is_none() && sha512.is_none() && md5.is_none() {
            None
        } else {
            Some(Self { sha1, sha512, md5 })
        }
    }
}

pub struct Report {
    pub resolved: usize,
    pub failed: usize,
}

/// Collect the project ids present in an existing lockfile, so the search
/// results can mark deps that are in the pack even when they're only in the
/// lockfile (not in the manifest). Returns (modrinth slugs, curseforge ids).
pub fn read_known_ids(dir: &Path) -> (std::collections::HashSet<String>, std::collections::HashSet<i64>) {
    let mut slugs = std::collections::HashSet::new();
    let mut cf_ids = std::collections::HashSet::new();
    let Ok(raw) = std::fs::read_to_string(dir.join(LOCK_FILE)) else {
        return (slugs, cf_ids);
    };
    let Ok(toml) = toml::from_str::<toml::Value>(&raw) else {
        return (slugs, cf_ids);
    };
    for key in ["mod", "resourcepack", "datapack", "shader"] {
        let Some(arr) = toml.get(key).and_then(|v| v.as_array()) else {
            continue;
        };
        for entry in arr {
            if let Some(slug) = entry
                .get("modrinth")
                .and_then(|v| v.get("slug"))
                .and_then(|v| v.as_str())
            {
                slugs.insert(slug.to_owned());
            }
            if let Some(pid) = entry
                .get("curseforge")
                .and_then(|v| v.get("project_id"))
                .and_then(|v| v.as_integer())
            {
                cf_ids.insert(pid);
            }
        }
    }
    (slugs, cf_ids)
}

/// Resolve every manifest entry and rewrite Easypacker.lock. The lockfile is
/// purely derived from the TOML manifest: deps not present in the manifest
/// resolve to the highest matching version; deps the player pinned (via the
/// dependency popup, which writes them into the manifest) resolve to the
/// pinned version. UI actions never edit the lockfile directly.
pub async fn generate(dir: &Path, cfg: &Config) -> Result<Report> {
    let manifest = Manifest::load(dir)?;
    let proj = &manifest.project;

    let mut targets: Vec<String> = proj
        .platforms
        .iter()
        .map(|p| p.to_lowercase())
        .filter(|p| p == "modrinth" || p == "curseforge")
        .collect();
    targets.sort_unstable();
    targets.dedup();
    if targets.is_empty() {
        targets.push("modrinth".into());
    }
    let want_mr = targets.iter().any(|t| t == "modrinth");
    let want_cf = targets.iter().any(|t| t == "curseforge");

    let cf = if want_cf {
        let key = cfg.get_api_key(None);
        if key.is_err() {
            eprintln!("easypacker: no CurseForge API key — CurseForge pins skipped");
        }
        key.ok().map(|k| Arc::new(CurseForgeClient::new(&k)))
    } else {
        None
    };

    let mut set = tokio::task::JoinSet::new();
    let mut requested = 0usize;
    for (cat, class_id) in CATEGORIES {
        for (id, spec) in manifest.cat(cat).iter() {
            requested += 1;
            let id = id.clone();
            let spec = spec.clone();
            let mc = proj.minecraft.clone();
            let loader = proj.loader.clone();
            let cf = cf.clone();
            let want_cf = cf.is_some();
            set.spawn(async move {
                let (entry, warnings) =
                    resolve_entry(cat, class_id, &id, &spec, &mc, &loader, want_mr, want_cf, cf)
                        .await;
                (cat, id, entry, warnings)
            });
        }
    }

    let (mut resolved, mut failed) = (BTreeMap::new(), 0usize);
    while let Some(joined) = set.join_next().await {
        match joined {
            Ok((cat, id, Ok(entry), warnings)) => {
                for w in warnings {
                    eprintln!("easypacker: {cat}/{id}: {w}");
                }
                resolved.insert((cat, id), entry);
            }
            Ok((cat, id, Err(e), _)) => {
                failed += 1;
                eprintln!("easypacker: {cat}/{id}: {e}");
            }
            Err(e) => {
                failed += 1;
                eprintln!("easypacker: resolver task failed: {e}");
            }
        }
    }

    // Don't clobber a good lockfile when everything failed (e.g. offline).
    if requested > 0 && resolved.is_empty() {
        bail!("all {requested} entries failed to resolve; keeping existing lockfile");
    }

    let resolved_count = resolved.len();
    let manifest_ids: HashSet<String> = manifest
        .mods
        .keys()
        .chain(manifest.resourcepacks.keys())
        .chain(manifest.datapacks.keys())
        .chain(manifest.shaders.keys())
        .cloned()
        .collect();

    // Resolve transitive dependencies (cargo-style): each manifest entry
    // declares dep ids; unresolved ones become their own lock rows.
    let dep_entries = resolve_dependencies(
        &mut resolved,
        &manifest_ids,
        &proj.minecraft,
        &proj.loader,
        want_mr,
        want_cf,
        cf.clone(),
    )
    .await;

    let (mut mods, mut resourcepacks, mut datapacks, mut shaders) =
        (Vec::new(), Vec::new(), Vec::new(), Vec::new());
    for ((cat, _), entry) in resolved {
        match cat {
            "mod" => mods.push(entry),
            "resourcepack" => resourcepacks.push(entry),
            "datapack" => datapacks.push(entry),
            _ => shaders.push(entry),
        }
    }
    mods.extend(dep_entries);

    let lock = Lock {
        minecraft: proj.minecraft.clone(),
        loader: proj.loader.clone(),
        targets,
        mod_: mods,
        resourcepack: resourcepacks,
        datapack: datapacks,
        shader: shaders,
    };

    std::fs::write(dir.join(LOCK_FILE), render(&lock))?;

    Ok(Report {
        resolved: resolved_count,
        failed,
    })
}

type ResolveOut = (Result<LockEntry, String>, Vec<String>);

#[allow(clippy::too_many_arguments)]
async fn resolve_entry(
    cat: &'static str,
    class_id: i32,
    id: &str,
    spec: &ModSpec,
    mc: &str,
    loader: &str,
    want_mr: bool,
    want_cf: bool,
    cf: Option<Arc<CurseForgeClient>>,
) -> ResolveOut {
    let is_mod = cat == "mod";
    let mut warnings = Vec::new();
    let mut name: Option<String> = None;
    let mut version_name: Option<String> = spec.shared_version();
    let mut mr_lock = None;
    let mut cf_lock = None;

    // Only query platforms the spec actually targets.
    let has_mr = spec.has_modrinth();
    let has_cf = spec.has_curseforge();
    let want_mr = want_mr && has_mr;
    let want_cf = want_cf && has_cf;

    if want_mr {
        match resolve_modrinth(id, spec, mc, loader, is_mod).await {
            Ok((title, vname, l)) => {
                name = Some(title);
                if version_name.is_none() {
                    version_name = Some(vname);
                }
                mr_lock = Some(l);
            }
            Err(e) => warnings.push(e),
        }
    }
    if want_cf
        && let Some(ref client) = cf
    {
        match resolve_curseforge(client, class_id, id, spec, mc, loader, is_mod).await {
            Ok((title, vname, l)) => {
                if name.is_none() || title != id {
                    name.get_or_insert(title);
                }
                if version_name.is_none() {
                    version_name = Some(vname);
                }
                cf_lock = Some(l);
            }
            Err(e) => warnings.push(e),
        }
    }

    if mr_lock.is_none() && cf_lock.is_none() {
        return (Err(warnings.join("; ")), warnings);
    }

    (
        Ok(LockEntry {
            id: id.to_owned(),
            name: name.unwrap_or_else(|| id.to_owned()),
            version: version_name.unwrap_or_default(),
            modrinth: mr_lock,
            curseforge: cf_lock,
        }),
        warnings,
    )
}

async fn resolve_modrinth(
    id: &str,
    spec: &ModSpec,
    mc: &str,
    loader: &str,
    is_mod: bool,
) -> Result<(String, String, LockModrinth), String> {
    let slug = spec.modrinth_slug(id);
    let loader_filter = if is_mod && !loader.is_empty() {
        Some(loader)
    } else {
        None
    };
    let mc_filter = if mc.is_empty() { None } else { Some(mc) };
    let (project, versions) = tokio::join!(
        ModrinthClient::get_project(&slug),
        ModrinthClient::get_versions(&slug, mc_filter, loader_filter),
    );
    let project = project.map_err(|e| format!("modrinth: {e}"))?;
    let versions = versions.map_err(|e| format!("modrinth: {e}"))?;
    let requested = spec.version_for(true);
    // No requested version => latest (API returns newest first).
    let v = versions
        .iter()
        .find(|v| {
            requested.as_ref().is_none_or(|req| {
                *req == v.name || *req == v.version_number || *req == v.id
            })
        })
        .ok_or_else(|| {
            format!(
                "modrinth: version \"{}\" not found for {slug}",
                requested.unwrap_or_default()
            )
        })?;
    Ok((
        project.title,
        v.name.clone(),
        LockModrinth {
            slug: project.slug,
            project_id: project.id,
            version_id: v.id.clone(),
            filename: v.filename.clone(),
            url: v.url.clone(),
            size: v.size,
            hashes: LockHashes::new(v.sha1.clone(), v.sha512.clone(), None),
            dependencies: v
                .dependencies
                .iter()
                .filter(|d| d.kind == DepKind::Required || d.kind == DepKind::Optional)
                .map(|d| LockDep {
                    id: d.project_id.clone(),
                    optional: d.kind == DepKind::Optional,
                })
                .collect(),
        },
    ))
}

async fn resolve_curseforge(
    client: &CurseForgeClient,
    class_id: i32,
    id: &str,
    spec: &ModSpec,
    mc: &str,
    loader: &str,
    is_mod: bool,
) -> Result<(String, String, LockCurseForge), String> {
    let (mod_id, title) = match spec.curseforge_project_id() {
        Some(pid) => (
            i32::try_from(pid).map_err(|_| format!("curseforge: projectId {pid} out of range"))?,
            id.to_owned(),
        ),
        None => client
            .find_by_slug(id, Some(class_id))
            .await
            .map_err(|e| format!("curseforge: {e}"))?
            .ok_or_else(|| format!("curseforge: no project with slug \"{id}\""))?,
    };
    let loader_filter = if is_mod && !loader.is_empty() {
        Some(loader)
    } else {
        None
    };
    let mc_filter = if mc.is_empty() { None } else { Some(mc) };
    let files = client
        .get_files(mod_id, mc_filter, loader_filter)
        .await
        .map_err(|e| format!("curseforge: {e}"))?;
    let requested = spec.version_for(false);
    let f = files
        .iter()
        .find(|f| {
            requested.as_ref().is_none_or(|req| {
                *req == f.display_name || *req == f.file_name || *req == f.id.to_string()
            })
        })
        .ok_or_else(|| {
            format!(
                "curseforge: version \"{}\" not found for {id}",
                requested.unwrap_or_default()
            )
        })?;
    Ok((
        title,
        f.display_name.clone(),
        LockCurseForge {
            project_id: i64::from(mod_id),
            file_id: i64::from(f.id),
            filename: f.file_name.clone(),
            url: f.download_url.clone(),
            size: f.file_length,
            hashes: LockHashes::new(f.sha1.clone(), None, f.md5.clone()),
            dependencies: f
                .dependencies
                .iter()
                .filter(|d| d.kind == DepKind::Required || d.kind == DepKind::Optional)
                .map(|d| LockDep {
                    id: d.project_id.clone(),
                    optional: d.kind == DepKind::Optional,
                })
                .collect(),
        },
    ))
}

/// Resolve a transitive dependency by Modrinth project id into a lock row.
/// Picks the highest matching version (the API returns newest first), and —
/// when the pack targets CurseForge too — tries to attach the counterpart
/// file so the dep is pinned on both platforms like any normal mod.
async fn resolve_dep_modrinth(
    dep_id: &str,
    mc: &str,
    loader: &str,
    want_cf: bool,
    cf: Option<Arc<CurseForgeClient>>,
) -> Result<LockEntry, String> {
    let loader_filter = if !loader.is_empty() { Some(loader) } else { None };
    let mc_filter = if mc.is_empty() { None } else { Some(mc) };
    let (project, versions) = tokio::join!(
        ModrinthClient::get_project(dep_id),
        ModrinthClient::get_versions(dep_id, mc_filter, loader_filter),
    );
    let project = project.map_err(|e| format!("modrinth dep {dep_id}: {e}"))?;
    let versions = versions.map_err(|e| format!("modrinth dep {dep_id}: {e}"))?;
    let slug = project.slug.clone();
    let v = versions
        .first()
        .ok_or_else(|| format!("modrinth dep {dep_id}: version not found"))?;

    // Cross-platform: try to find the same mod on CurseForge.
    let cf_lock = if want_cf && let Some(client) = cf.as_ref() {
        match client
            .find_by_slug(&slug, Some(6))
            .await
            .map_err(|e| eprintln!("easypacker: cf lookup for dep {slug}: {e}"))
        {
            Ok(Some((mod_id, _))) => match client.get_files(mod_id, mc_filter, loader_filter).await {
                Ok(files) => files.first().map(|f| LockCurseForge {
                    project_id: i64::from(mod_id),
                    file_id: i64::from(f.id),
                    filename: f.file_name.clone(),
                    url: f.download_url.clone(),
                    size: f.file_length,
                    hashes: LockHashes::new(f.sha1.clone(), None, f.md5.clone()),
                    dependencies: f
                        .dependencies
                        .iter()
                        .filter(|d| d.kind == DepKind::Required || d.kind == DepKind::Optional)
                        .map(|d| LockDep {
                            id: d.project_id.clone(),
                            optional: d.kind == DepKind::Optional,
                        })
                        .collect(),
                }),
                Err(e) => {
                    eprintln!("easypacker: cf files for dep {slug}: {e}");
                    None
                }
            },
            _ => None,
        }
    } else {
        None
    };

    Ok(LockEntry {
        id: slug,
        name: project.title,
        version: v.name.clone(),
        modrinth: Some(LockModrinth {
            slug: project.slug,
            project_id: project.id,
            version_id: v.id.clone(),
            filename: v.filename.clone(),
            url: v.url.clone(),
            size: v.size,
            hashes: LockHashes::new(v.sha1.clone(), v.sha512.clone(), None),
            dependencies: v
                .dependencies
                .iter()
                .filter(|d| d.kind == DepKind::Required || d.kind == DepKind::Optional)
                .map(|d| LockDep {
                    id: d.project_id.clone(),
                    optional: d.kind == DepKind::Optional,
                })
                .collect(),
        }),
        curseforge: cf_lock,
    })
}

/// Resolve a transitive dependency by CurseForge mod id into a lock row.
/// Picks the highest matching file, and — when the pack targets Modrinth
/// too — tries to attach the counterpart version.
async fn resolve_dep_curseforge(
    client: &CurseForgeClient,
    dep_id: i32,
    mc: &str,
    loader: &str,
    want_mr: bool,
) -> Result<LockEntry, String> {
    let (mod_id, title, slug) = client
        .get_mod(dep_id)
        .await
        .map_err(|e| format!("cf dep {dep_id}: {e}"))?;
    let loader_filter = if !loader.is_empty() { Some(loader) } else { None };
    let mc_filter = if mc.is_empty() { None } else { Some(mc) };
    let files = client
        .get_files(mod_id, mc_filter, loader_filter)
        .await
        .map_err(|e| format!("cf dep {dep_id}: {e}"))?;
    let f = files
        .first()
        .ok_or_else(|| format!("cf dep {dep_id}: version not found"))?;

    // Cross-platform: try to find the same mod on Modrinth.
    let mr_lock = if want_mr {
        match ModrinthClient::get_project(&slug).await {
            Ok(project) => {
                match ModrinthClient::get_versions(&slug, mc_filter, loader_filter).await {
                    Ok(versions) => versions.first().map(|v| LockModrinth {
                        slug: project.slug.clone(),
                        project_id: project.id,
                        version_id: v.id.clone(),
                        filename: v.filename.clone(),
                        url: v.url.clone(),
                        size: v.size,
                        hashes: LockHashes::new(v.sha1.clone(), v.sha512.clone(), None),
                        dependencies: v
                            .dependencies
                            .iter()
                            .filter(|d| d.kind == DepKind::Required || d.kind == DepKind::Optional)
                            .map(|d| LockDep {
                                id: d.project_id.clone(),
                                optional: d.kind == DepKind::Optional,
                            })
                            .collect(),
                    }),
                    Err(e) => {
                        eprintln!("easypacker: mr versions for dep {slug}: {e}");
                        None
                    }
                }
            }
            Err(_) => None,
        }
    } else {
        None
    };

    Ok(LockEntry {
        id: slug,
        name: title,
        version: f.display_name.clone(),
        modrinth: mr_lock,
        curseforge: Some(LockCurseForge {
            project_id: i64::from(mod_id),
            file_id: i64::from(f.id),
            filename: f.file_name.clone(),
            url: f.download_url.clone(),
            size: f.file_length,
            hashes: LockHashes::new(f.sha1.clone(), None, f.md5.clone()),
            dependencies: f
                .dependencies
                .iter()
                .filter(|d| d.kind == DepKind::Required || d.kind == DepKind::Optional)
                .map(|d| LockDep {
                    id: d.project_id.clone(),
                    optional: d.kind == DepKind::Optional,
                })
                .collect(),
        }),
    })
}

/// Resolve direct dependencies of manifest entries into their own lock rows.
/// Required deps are always pinned; optional deps are pinned only when the
/// Resolve direct dependencies of manifest entries into their own lock rows.
/// Required deps are always pinned; optional deps are only included when the
/// player enabled them (i.e. they're manifest entries, resolved separately).
/// Each resolved dep row uses the easypacker id (modrinth/cf slug), tries
/// both platforms the pack targets, and resolves the highest matching
/// version. Deps already in the manifest (pinned by the player) are skipped
/// here — the manifest entry covers them.
/// ponytail: one level deep — full transitive closure would walk each dep's
/// own deps; add a visited+BFS pass when the lockfile needs the full graph.
async fn resolve_dependencies(
    resolved: &mut BTreeMap<(&'static str, String), LockEntry>,
    manifest_ids: &HashSet<String>,
    mc: &str,
    loader: &str,
    want_mr: bool,
    want_cf: bool,
    cf: Option<Arc<CurseForgeClient>>,
) -> Vec<LockEntry> {
    // Gather (platform, raw dep_id, optional) edges across all resolved entries.
    let mut edges: Vec<(Platform, String, bool)> = Vec::new();
    for e in resolved.values() {
        if let Some(mr) = &e.modrinth {
            for d in &mr.dependencies {
                edges.push((Platform::Modrinth, d.id.clone(), d.optional));
            }
        }
        if let Some(cf) = &e.curseforge {
            for d in &cf.dependencies {
                edges.push((Platform::CurseForge, d.id.clone(), d.optional));
            }
        }
    }
    edges.sort_by(|a, b| a.1.cmp(&b.1));
    edges.dedup_by(|a, b| a.0 == b.0 && a.1 == b.1);
    if edges.is_empty() {
        return Vec::new();
    }

    let mut seen: HashSet<(Platform, String)> = HashSet::new();
    let mut set = tokio::task::JoinSet::new();
    for (platform, dep_id, optional) in &edges {
        if !seen.insert((platform.clone(), dep_id.clone())) {
            continue;
        }
        let id_str = dep_id.clone();
        let optional = *optional;
        match platform {
            Platform::Modrinth => {
                if !want_mr {
                    continue;
                }
                let mc = mc.to_owned();
                let loader = loader.to_owned();
                let cf = cf.clone();
                set.spawn(async move {
                    (
                        Platform::Modrinth,
                        id_str.clone(),
                        optional,
                        resolve_dep_modrinth(&id_str, &mc, &loader, want_cf, cf).await,
                    )
                });
            }
            Platform::CurseForge => {
                let Some(ref client) = cf else { continue };
                if !want_cf {
                    continue;
                }
                let Ok(mod_id) = dep_id.parse::<i32>() else { continue };
                let client = client.clone();
                let mc = mc.to_owned();
                let loader = loader.to_owned();
                set.spawn(async move {
                    (
                        Platform::CurseForge,
                        id_str.clone(),
                        optional,
                        resolve_dep_curseforge(&client, mod_id, &mc, &loader, want_mr).await,
                    )
                });
            }
        }
    }

    // raw id -> slug for every resolved dep (even ones we drop), so edges
    // can be rewritten to readable easypacker ids.
    let mut slug_of: std::collections::HashMap<(Platform, String), String> =
        std::collections::HashMap::new();
    let mut out: Vec<LockEntry> = Vec::new();
    let mut out_slugs: HashSet<String> = HashSet::new();
    while let Some(joined) = set.join_next().await {
        match joined {
            Ok((platform, raw_id, optional, Ok(entry))) => {
                let slug = entry.id.clone();
                slug_of.insert((platform.clone(), raw_id.clone()), slug.clone());
                // Optional deps are only added when the player enabled them,
                // which writes them into the manifest (resolved separately).
                if optional && !manifest_ids.contains(&slug) {
                    continue;
                }
                if !out_slugs.insert(slug.clone()) {
                    continue;
                }
                if manifest_ids.contains(&slug) {
                    continue; // already a manifest entry (resolved separately)
                }
                out.push(entry);
            }
            Ok((_, _, _, Err(e))) => eprintln!("easypacker: {e}"),
            Err(e) => eprintln!("easypacker: dep task failed: {e}"),
        }
    }

    // Rewrite each manifest entry's dep edges: raw id -> slug, and keep only
    // deps that are either a manifest entry or a kept dep row.
    let known: HashSet<String> = manifest_ids.iter().cloned().chain(out_slugs).collect();
    for e in resolved.values_mut() {
        rewrite_edges(e, &slug_of, &known);
    }
    for e in out.iter_mut() {
        rewrite_edges(e, &slug_of, &known);
    }

    // Stable order by id for reproducible lockfiles.
    out.sort_by(|a, b| a.id.cmp(&b.id));
    out
}

/// Rewrite an entry's dependency ids from raw project ids to easypacker slugs,
/// keeping only deps that are actually in the pack (manifest entry or dep row)
/// AND required (optional deps never appear in the edge list).
fn rewrite_edges(
    e: &mut LockEntry,
    slug_of: &std::collections::HashMap<(Platform, String), String>,
    known: &HashSet<String>,
) {
    if let Some(mr) = &mut e.modrinth {
        mr.dependencies = mr
            .dependencies
            .iter()
            .filter_map(|d| {
                if d.optional {
                    return None;
                }
                let slug = slug_of
                    .get(&(Platform::Modrinth, d.id.clone()))
                    .cloned()
                    .unwrap_or_else(|| d.id.clone());
                known.contains(&slug).then(|| LockDep {
                    id: slug,
                    optional: false,
                })
            })
            .collect();
    }
    if let Some(cf) = &mut e.curseforge {
        cf.dependencies = cf
            .dependencies
            .iter()
            .filter_map(|d| {
                if d.optional {
                    return None;
                }
                let slug = slug_of
                    .get(&(Platform::CurseForge, d.id.clone()))
                    .cloned()
                    .unwrap_or_else(|| d.id.clone());
                known.contains(&slug).then(|| LockDep {
                    id: slug,
                    optional: false,
                })
            })
            .collect();
    }
}

/// Render fields as a multi-line inline table (TOML 1.1), e.g.
/// `{
///    slug = "sodium",
///    ...
/// }` indented to `indent` levels.
fn inline_table(fields: &[String], indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let body = fields
        .iter()
        .map(|f| format!("{pad}{f}"))
        .collect::<Vec<_>>()
        .join(",\n");
    format!("{{\n{body}\n{}}}", "    ".repeat(indent - 1))
}

fn render_hashes(h: &LockHashes, indent: usize) -> String {
    let mut fields = Vec::new();
    if let Some(s) = &h.sha1 {
        fields.push(format!("sha1 = {}", tstr(s)));
    }
    if let Some(s) = &h.sha512 {
        fields.push(format!("sha512 = {}", tstr(s)));
    }
    if let Some(s) = &h.md5 {
        fields.push(format!("md5 = {}", tstr(s)));
    }
    inline_table(&fields, indent)
}

fn render(lock: &Lock) -> String {
    let mut out = String::from(LOCK_HEADER);
    out.push_str("version = 1\n");
    writeln!(out, "minecraft = {}", tstr(&lock.minecraft)).unwrap();
    writeln!(out, "loader = {}", tstr(&lock.loader)).unwrap();
    let targets = lock
        .targets
        .iter()
        .map(|t| tstr(t))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(out, "targets = [{targets}]").unwrap();

    let categories: [(&str, &Vec<LockEntry>); 4] = [
        ("mod", &lock.mod_),
        ("resourcepack", &lock.resourcepack),
        ("datapack", &lock.datapack),
        ("shader", &lock.shader),
    ];
    for (cat, entries) in categories {
        for e in entries {
            writeln!(out, "\n[[{cat}]]").unwrap();
            writeln!(out, "id = {}", tstr(&e.id)).unwrap();
            writeln!(out, "name = {}", tstr(&e.name)).unwrap();
            writeln!(out, "version = {}", tstr(&e.version)).unwrap();
            if let Some(mr) = &e.modrinth {
                let mut fields = vec![
                    format!("slug = {}", tstr(&mr.slug)),
                    format!("project_id = {}", tstr(&mr.project_id)),
                    format!("version_id = {}", tstr(&mr.version_id)),
                    format!("filename = {}", tstr(&mr.filename)),
                ];
                if let Some(url) = &mr.url {
                    fields.push(format!("url = {}", tstr(url)));
                }
                fields.push(format!("size = {}", mr.size));
                if let Some(h) = &mr.hashes {
                    fields.push(format!("hashes = {}", render_hashes(h, 2)));
                }
                writeln!(out, "modrinth = {}", inline_table(&fields, 1)).unwrap();
            }
            if let Some(cf) = &e.curseforge {
                let mut fields = vec![
                    format!("project_id = {}", cf.project_id),
                    format!("file_id = {}", cf.file_id),
                    format!("filename = {}", tstr(&cf.filename)),
                ];
                if let Some(url) = &cf.url {
                    fields.push(format!("url = {}", tstr(url)));
                }
                fields.push(format!("size = {}", cf.size));
                if let Some(h) = &cf.hashes {
                    fields.push(format!("hashes = {}", render_hashes(h, 2)));
                }
                writeln!(out, "curseforge = {}", inline_table(&fields, 1)).unwrap();
            }
            // Dependency edges (cargo-style): list the ids this entry pins,
            // one per line like Cargo.lock.
            let deps = collect_dep_ids(e);
            if !deps.is_empty() {
                writeln!(out, "dependencies = [").unwrap();
                for d in &deps {
                    writeln!(out, "    {},", tstr(d)).unwrap();
                }
                writeln!(out, "]").unwrap();
            }
        }
    }
    out
}

/// Resolve ids declared by this entry across whichever platforms it pins.
fn collect_dep_ids(e: &LockEntry) -> Vec<String> {
    let mut ids: Vec<String> = Vec::new();
    if let Some(mr) = &e.modrinth {
        ids.extend(mr.dependencies.iter().map(|d| d.id.clone()));
    }
    if let Some(cf) = &e.curseforge {
        ids.extend(cf.dependencies.iter().map(|d| d.id.clone()));
    }
    ids.sort();
    ids.dedup();
    ids
}

/// (platform, dep id, optional) edges gathered from all resolved entries.
#[cfg(test)]
#[path = "../tests/lock_tests.rs"]
mod tests;
