//! Easypacker.lock generation — resolves Easypacker.toml against
//! Modrinth/CurseForge and pins exact files, download urls and hashes.
//! Regenerated on every run; never edit by hand (cargo-style).

use crate::api::{CurseForgeClient, ModrinthClient};
use crate::config::Config;
use crate::project::{CATEGORIES, Manifest, ModSpec, tstr};
use color_eyre::eyre::{Result, bail};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;
use std::sync::Arc;

pub const LOCK_FILE: &str = "Easypacker.lock";
const LOCK_HEADER: &str = "# This file is automatically @generated by Easypacker.\n# It is not intended for manual editing.\n";

struct Lock {
    minecraft: String,
    targets: Vec<String>,
    mod_: Vec<LockEntry>,
    resourcepack: Vec<LockEntry>,
    datapack: Vec<LockEntry>,
    shader: Vec<LockEntry>,
}

struct LockEntry {
    id: String,
    name: String,
    version: String,
    modrinth: Option<LockModrinth>,
    curseforge: Option<LockCurseForge>,
}

struct LockModrinth {
    slug: String,
    project_id: String,
    version_id: String,
    filename: String,
    url: Option<String>,
    size: u64,
    hashes: Option<LockHashes>,
}

struct LockCurseForge {
    project_id: i64,
    file_id: i64,
    filename: String,
    url: Option<String>,
    size: u64,
    hashes: Option<LockHashes>,
}

struct LockHashes {
    sha1: Option<String>,
    sha512: Option<String>,
    md5: Option<String>,
}

impl LockHashes {
    fn new(sha1: Option<String>, sha512: Option<String>, md5: Option<String>) -> Option<Self> {
        if sha1.is_none() && sha512.is_none() && md5.is_none() {
            None
        } else {
            Some(Self { sha1, sha512, md5 })
        }
    }
}

pub struct Report {
    pub resolved: usize,
    pub failed: usize,
}

/// Resolve every manifest entry and rewrite Easypacker.lock.
pub async fn generate(dir: &Path, cfg: &Config) -> Result<Report> {
    let manifest = Manifest::load(dir)?;
    let proj = &manifest.project;

    let mut targets: Vec<String> = proj
        .platforms
        .iter()
        .map(|p| p.to_lowercase())
        .filter(|p| p == "modrinth" || p == "curseforge")
        .collect();
    targets.sort_unstable();
    targets.dedup();
    if targets.is_empty() {
        targets.push("modrinth".into());
    }
    let want_mr = targets.iter().any(|t| t == "modrinth");
    let want_cf = targets.iter().any(|t| t == "curseforge");

    let cf = if want_cf {
        let key = cfg.get_api_key(None);
        if key.is_err() {
            eprintln!("easypacker: no CurseForge API key — CurseForge pins skipped");
        }
        key.ok().map(|k| Arc::new(CurseForgeClient::new(&k)))
    } else {
        None
    };

    let mut set = tokio::task::JoinSet::new();
    let mut requested = 0usize;
    for (cat, class_id) in CATEGORIES {
        for (id, spec) in manifest.cat(cat).iter() {
            requested += 1;
            let id = id.clone();
            let spec = spec.clone();
            let mc = proj.minecraft.clone();
            let loader = proj.loader.clone();
            let cf = cf.clone();
            let want_cf = cf.is_some();
            set.spawn(async move {
                let (entry, warnings) =
                    resolve_entry(cat, class_id, &id, &spec, &mc, &loader, want_mr, want_cf, cf)
                        .await;
                (cat, id, entry, warnings)
            });
        }
    }

    let (mut resolved, mut failed) = (BTreeMap::new(), 0usize);
    while let Some(joined) = set.join_next().await {
        match joined {
            Ok((cat, id, Ok(entry), warnings)) => {
                for w in warnings {
                    eprintln!("easypacker: {cat}/{id}: {w}");
                }
                resolved.insert((cat, id), entry);
            }
            Ok((cat, id, Err(e), _)) => {
                failed += 1;
                eprintln!("easypacker: {cat}/{id}: {e}");
            }
            Err(e) => {
                failed += 1;
                eprintln!("easypacker: resolver task failed: {e}");
            }
        }
    }

    // Don't clobber a good lockfile when everything failed (e.g. offline).
    if requested > 0 && resolved.is_empty() {
        bail!("all {requested} entries failed to resolve; keeping existing lockfile");
    }

    let resolved_count = resolved.len();
    let (mut mods, mut resourcepacks, mut datapacks, mut shaders) =
        (Vec::new(), Vec::new(), Vec::new(), Vec::new());
    for ((cat, _), entry) in resolved {
        match cat {
            "mod" => mods.push(entry),
            "resourcepack" => resourcepacks.push(entry),
            "datapack" => datapacks.push(entry),
            _ => shaders.push(entry),
        }
    }

    let lock = Lock {
        minecraft: proj.minecraft.clone(),
        targets,
        mod_: mods,
        resourcepack: resourcepacks,
        datapack: datapacks,
        shader: shaders,
    };

    std::fs::write(dir.join(LOCK_FILE), render(&lock))?;

    Ok(Report {
        resolved: resolved_count,
        failed,
    })
}

type ResolveOut = (Result<LockEntry, String>, Vec<String>);

#[allow(clippy::too_many_arguments)]
async fn resolve_entry(
    cat: &'static str,
    class_id: i32,
    id: &str,
    spec: &ModSpec,
    mc: &str,
    loader: &str,
    want_mr: bool,
    want_cf: bool,
    cf: Option<Arc<CurseForgeClient>>,
) -> ResolveOut {
    let is_mod = cat == "mod";
    let mut warnings = Vec::new();
    let mut name: Option<String> = None;
    let mut version_name: Option<String> = spec.shared_version();
    let mut mr_lock = None;
    let mut cf_lock = None;

    if want_mr {
        match resolve_modrinth(id, spec, mc, loader, is_mod).await {
            Ok((title, vname, l)) => {
                name = Some(title);
                if version_name.is_none() {
                    version_name = Some(vname);
                }
                mr_lock = Some(l);
            }
            Err(e) => warnings.push(e),
        }
    }
    if want_cf
        && let Some(ref client) = cf
    {
        match resolve_curseforge(client, class_id, id, spec, mc, loader, is_mod).await {
            Ok((title, vname, l)) => {
                if name.is_none() || title != id {
                    name.get_or_insert(title);
                }
                if version_name.is_none() {
                    version_name = Some(vname);
                }
                cf_lock = Some(l);
            }
            Err(e) => warnings.push(e),
        }
    }

    if mr_lock.is_none() && cf_lock.is_none() {
        return (Err(warnings.join("; ")), warnings);
    }

    (
        Ok(LockEntry {
            id: id.to_owned(),
            name: name.unwrap_or_else(|| id.to_owned()),
            version: version_name.unwrap_or_default(),
            modrinth: mr_lock,
            curseforge: cf_lock,
        }),
        warnings,
    )
}

async fn resolve_modrinth(
    id: &str,
    spec: &ModSpec,
    mc: &str,
    loader: &str,
    is_mod: bool,
) -> Result<(String, String, LockModrinth), String> {
    let slug = spec.modrinth_slug(id);
    let loader_filter = if is_mod && !loader.is_empty() {
        Some(loader)
    } else {
        None
    };
    let mc_filter = if mc.is_empty() { None } else { Some(mc) };
    let (project, versions) = tokio::join!(
        ModrinthClient::get_project(&slug),
        ModrinthClient::get_versions(&slug, mc_filter, loader_filter),
    );
    let project = project.map_err(|e| format!("modrinth: {e}"))?;
    let versions = versions.map_err(|e| format!("modrinth: {e}"))?;
    let requested = spec.version_for(true);
    // No requested version => latest (API returns newest first).
    let v = versions
        .iter()
        .find(|v| {
            requested.as_ref().is_none_or(|req| {
                *req == v.name || *req == v.version_number || *req == v.id
            })
        })
        .ok_or_else(|| {
            format!(
                "modrinth: version \"{}\" not found for {slug}",
                requested.unwrap_or_default()
            )
        })?;
    Ok((
        project.title,
        v.name.clone(),
        LockModrinth {
            slug: project.slug,
            project_id: project.id,
            version_id: v.id.clone(),
            filename: v.filename.clone(),
            url: v.url.clone(),
            size: v.size,
            hashes: LockHashes::new(v.sha1.clone(), v.sha512.clone(), None),
        },
    ))
}

async fn resolve_curseforge(
    client: &CurseForgeClient,
    class_id: i32,
    id: &str,
    spec: &ModSpec,
    mc: &str,
    loader: &str,
    is_mod: bool,
) -> Result<(String, String, LockCurseForge), String> {
    let (mod_id, title) = match spec.curseforge_project_id() {
        Some(pid) => (
            i32::try_from(pid).map_err(|_| format!("curseforge: projectId {pid} out of range"))?,
            id.to_owned(),
        ),
        None => client
            .find_by_slug(id, Some(class_id))
            .await
            .map_err(|e| format!("curseforge: {e}"))?
            .ok_or_else(|| format!("curseforge: no project with slug \"{id}\""))?,
    };
    let loader_filter = if is_mod && !loader.is_empty() {
        Some(loader)
    } else {
        None
    };
    let mc_filter = if mc.is_empty() { None } else { Some(mc) };
    let files = client
        .get_files(mod_id, mc_filter, loader_filter)
        .await
        .map_err(|e| format!("curseforge: {e}"))?;
    let requested = spec.version_for(false);
    let f = files
        .iter()
        .find(|f| {
            requested.as_ref().is_none_or(|req| {
                *req == f.display_name || *req == f.file_name || *req == f.id.to_string()
            })
        })
        .ok_or_else(|| {
            format!(
                "curseforge: version \"{}\" not found for {id}",
                requested.unwrap_or_default()
            )
        })?;
    Ok((
        title,
        f.display_name.clone(),
        LockCurseForge {
            project_id: i64::from(mod_id),
            file_id: i64::from(f.id),
            filename: f.file_name.clone(),
            url: f.download_url.clone(),
            size: f.file_length,
            hashes: LockHashes::new(f.sha1.clone(), None, f.md5.clone()),
        },
    ))
}

/// Render fields as a multi-line inline table (TOML 1.1), e.g.
/// `{
///    slug = "sodium",
///    ...
/// }` indented to `indent` levels.
fn inline_table(fields: &[String], indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let body = fields
        .iter()
        .map(|f| format!("{pad}{f}"))
        .collect::<Vec<_>>()
        .join(",\n");
    format!("{{\n{body}\n{}}}", "    ".repeat(indent - 1))
}

fn render_hashes(h: &LockHashes, indent: usize) -> String {
    let mut fields = Vec::new();
    if let Some(s) = &h.sha1 {
        fields.push(format!("sha1 = {}", tstr(s)));
    }
    if let Some(s) = &h.sha512 {
        fields.push(format!("sha512 = {}", tstr(s)));
    }
    if let Some(s) = &h.md5 {
        fields.push(format!("md5 = {}", tstr(s)));
    }
    inline_table(&fields, indent)
}

fn render(lock: &Lock) -> String {
    let mut out = String::from(LOCK_HEADER);
    out.push_str("version = 1\n");
    writeln!(out, "minecraft = {}", tstr(&lock.minecraft)).unwrap();
    let targets = lock
        .targets
        .iter()
        .map(|t| tstr(t))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(out, "targets = [{targets}]").unwrap();

    let categories: [(&str, &Vec<LockEntry>); 4] = [
        ("mod", &lock.mod_),
        ("resourcepack", &lock.resourcepack),
        ("datapack", &lock.datapack),
        ("shader", &lock.shader),
    ];
    for (cat, entries) in categories {
        for e in entries {
            writeln!(out, "\n[[{cat}]]").unwrap();
            writeln!(out, "id = {}", tstr(&e.id)).unwrap();
            writeln!(out, "name = {}", tstr(&e.name)).unwrap();
            writeln!(out, "version = {}", tstr(&e.version)).unwrap();
            if let Some(mr) = &e.modrinth {
                let mut fields = vec![
                    format!("slug = {}", tstr(&mr.slug)),
                    format!("project_id = {}", tstr(&mr.project_id)),
                    format!("version_id = {}", tstr(&mr.version_id)),
                    format!("filename = {}", tstr(&mr.filename)),
                ];
                if let Some(url) = &mr.url {
                    fields.push(format!("url = {}", tstr(url)));
                }
                fields.push(format!("size = {}", mr.size));
                if let Some(h) = &mr.hashes {
                    fields.push(format!("hashes = {}", render_hashes(h, 2)));
                }
                writeln!(out, "modrinth = {}", inline_table(&fields, 1)).unwrap();
            }
            if let Some(cf) = &e.curseforge {
                let mut fields = vec![
                    format!("project_id = {}", cf.project_id),
                    format!("file_id = {}", cf.file_id),
                    format!("filename = {}", tstr(&cf.filename)),
                ];
                if let Some(url) = &cf.url {
                    fields.push(format!("url = {}", tstr(url)));
                }
                fields.push(format!("size = {}", cf.size));
                if let Some(h) = &cf.hashes {
                    fields.push(format!("hashes = {}", render_hashes(h, 2)));
                }
                writeln!(out, "curseforge = {}", inline_table(&fields, 1)).unwrap();
            }
        }
    }
    out
}

#[cfg(test)]
mod tests;
